version: "3.5"

services:
  app:
    container_name: wishlist_be
    build:
      context: .
    #image: 'wishlist:0.0.1-SNAPSHOT'
    ports:
      - "8080:8080"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_URL: "jdbc:postgresql://db:5432/mydb"

    depends_on:
      - db

  db:
    container_name: wishlist_postgres_db
    image: 'postgres:14.5-alpine'
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

