version: "3.5"

services:
  app:
    container_name: wishlist_be
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_URL: "jdbc:postgresql://db:5432/mydb"

    depends_on:
      - db

  db:
    container_name: wishlist_postgres_db
    image: 'postgres:14.5-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
